export const MAIL_TEMPLATE_PROVIDER: string = "MAIL_TEMPLATE_PROVIDER";
export const MAIL_TEMPLATE_PATH: string = "MAIL_TEMPLATE_PATH";
export const SMTP_TRANSPORT_CONFIGURATION: string = "SMTP_TRANSPORT_CONFIGURATION";