import { craftCurrentDisease, craftDiagnosticHeader, craftFamilyHistory, CraftItemFunc, craftJobAccident, craftLabel, craftMedicalAndSurgicalHistory, craftMedicalConsultation, craftMedicalDiagnostic, craftMedicalFitnessForJob, craftOccupationalDisease, craftPhysicalRegionalExam, craftRecommendation, CraftRecordFunc, craftReviewOfOrgansAndSystem, craftSpecificAndGeneralResults, craftToxicHabitsAndLifeStyle, craftVitalSignsAndAnthropometry, flatRecord } from "../generic-record-helper";
import { PeriodicRecord } from "@omega/medical/application/type/periodic-record";
import { craftCell, craftHeader, craftRow, craftSpacing, craftTitle, emptyCell, Row } from "../table.helper";

export const createPeriodicRecord: CraftRecordFunc<PeriodicRecord> = (record: PeriodicRecord, { fileNumber }) => flatRecord([
    craftHeader('A. Datos del Establecimiento - Empresa y Usuario'),
    institutionLayout({ ...record, fileNumber }),
    craftRow(craftSpacing({ colSpan: 70 })),
    craftHeader('B. Motivo de Consulta'),
    craftMedicalConsultation(record),
    craftHeader('C. Antecedentes Personales'),
    craftMedicalAndSurgicalHistory(record),
    craftToxicHabitsAndLifeStyle({
        tobacco: { ...record.toxicHabitTobacco },
        alcohol: { ...record.toxicHabitAlcohol },
        other: { ...record.toxicHabitOther },
    }, record),
    craftMedicalIncident(record),
    craftJobAccident(record),
    craftOccupationalDisease(record),
    craftHeader('D. Antecedentes Familiares (detallar el parentesco)'),
    craftFamilyHistory(record),
    craftHeader('E. Factores de riesgo del puesto de trabajo'),
    jobRiskLayout(record),
    craftRow(emptyCell({ colSpan: 70 })),
    jobRiskPreventionLayout(record),
    craftHeader('F. Enfermedad Actual'),
    craftCurrentDisease(record),
    craftRow(craftSpacing({ colSpan: 70 })),
    craftHeader('G. Revisión Actual de Órganos y Sistemas'),
    craftReviewOfOrgansAndSystem(record),
    craftRow(craftSpacing({ colSpan: 70 })),
    craftHeader('H. Constantes Vitales y Antropometría'),
    craftVitalSignsAndAnthropometry(record),
    craftRow(craftSpacing({ colSpan: 70 })),
    craftHeader('I. Examen Físico Regional'),
    craftPhysicalRegionalExam(record),
    craftRow(craftSpacing({ colSpan: 70 })),
    craftHeader('J. Resultados de Exámenes Generales y Específicos de Acuerdo al Riesgo y Puesto de Trabajo (imagen, laboratorio y otros)'),
    craftSpecificAndGeneralResults(record),
    craftRow(craftSpacing({ colSpan: 70 })),
    craftDiagnosticHeader('K. Diagnóstico'),
    craftMedicalDiagnostic(record.diagnostics),
    craftRow(craftSpacing({ colSpan: 70 })),
    craftHeader('L. Aptitud Médica para el Trabajo'),
    craftMedicalFitnessForJob(record),
    craftRow(craftSpacing({ colSpan: 70 })),
    craftHeader('M. Recomendaciones y/o Tratamiento'),
    craftRecommendation(record)
]);

const institutionLayout: CraftItemFunc<PeriodicRecord & {
    fileNumber: number;
}> = (record) => [
    craftRow(
        craftTitle('Institución del Sistema o Nombre de la Empresa', { colSpan: 16 }),
        craftTitle('RUC', { colSpan: 10 }),
        craftTitle('CIIU', { colSpan: 5 }),
        craftTitle('Establecimiento de Salud', { colSpan: 15 }),
        craftTitle('Número de Historia Clínica', { colSpan: 14 }),
        craftTitle('Número de Archivo', { colSpan: 10 }),
    ),
    craftRow(
        craftCell(record.companyName, { colSpan: 16 }),
        craftCell(record.companyRUC, { colSpan: 10 }),
        craftCell(record.companyCIIU ?? '', { colSpan: 5 }),
        craftCell(record.institutionHealthFacility, { colSpan: 15 }),
        craftCell(record.patientDni, { colSpan: 14 }),
        craftCell(record.fileNumber.toString().padStart(12, '0'), { colSpan: 10 }),
    ),
    craftRow(
        craftTitle('Primer apellido', { colSpan: 13 }),
        craftTitle('Segundo apellido', { colSpan: 13 }),
        craftTitle('Primer nombre', { colSpan: 13 }),
        craftTitle('Segundo nombre', { colSpan: 13 }),
        craftTitle('Sexo', { colSpan: 5 }),
        craftTitle('Puesto de trabajo (CIUO)', { colSpan: 13 }),
    ),
    craftRow(
        craftCell(record.patientLastName, { colSpan: 13 }),
        craftCell(record.patientSecondLastName, { colSpan: 13 }),
        craftCell(record.patientFirstName, { colSpan: 13 }),
        craftCell(record.patientMiddleName, { colSpan: 13 }),
        craftCell(record.patientGender === 'male' ? 'H' : 'M', { colSpan: 5, fontSize: 5 }),
        craftCell(record.jobPosition, { colSpan: 13 }),
    ),
];

export const craftMedicalIncident: CraftItemFunc<PeriodicRecord> = (record): Row[] => [
    craftRow(craftTitle('Incidentes', { colSpan: 70 })),
    craftLabel('Describir los principales incidentes suscitados'),
    craftRow(craftCell(record.medicalConsultationDescription, { border: ['left', 'right', 'bottom'], colSpan: 70 }))
]

const jobRiskLayout: CraftItemFunc<PeriodicRecord> = (record) => [
    craftRow(
        craftTitle('Puesto de trabajo / Área', { rowSpan: 2, colSpan: 9 }),
        craftTitle('Actividades', { rowSpan: 2, colSpan: 10 }),
        craftTitle('Tiempo de trabajo (meses)', { rowSpan: 2, colSpan: 5 }),
        craftTitle('Físico', { colSpan: 10 }),
        craftTitle('Mecánico', { colSpan: 15 }),
        craftTitle('Químico', { colSpan: 9 }),
        craftTitle('Biológico', { colSpan: 7 }),
        craftTitle('Ergonómico', { colSpan: 5 }),
    ),
    craftRow(
        craftCell('Temperaturas altas', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Temperaturas bajas', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Radiación Ionizante', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Radiación No Ionizante', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Ruido', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Vibración', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Iluminación', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Ventilación', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Fluido eléctrico', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Otros', { height: 150, orientation: 'vertical', style: 'itemTitle' }),

        craftCell('Atrapamiento entre máquinas', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Atrapamiento entre superficies', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Atrapamiento entre objetos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Caída de objetos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Caídas al mismo nivel', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Caídas a diferente nivel', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Contacto eléctrico', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Contacto con superficies de trabajos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Proyección de partículas - fragmentos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Proyección de fluidos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Pinchazos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Cortes', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Atropellamientos por vehículos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Choques / Colisión vehicular', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Otros', { height: 150, orientation: 'vertical', style: 'itemTitle' }),

        craftCell('Sólidos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Polvos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Humos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Líquidos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Vapores', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Aerosoles', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Neblinas', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Gaseosos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Otros', { height: 150, orientation: 'vertical', style: 'itemTitle' }),

        craftCell('Virus', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Hongos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Bacterias', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Parásitos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Exposición a vectores', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Exposición a animales selváticos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Otros', { height: 150, orientation: 'vertical', style: 'itemTitle' }),

        craftCell('Manejo manual de cargas', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Movimiento repetitivos', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Posturas forzadas', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Trabajos con PVD', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Otros', { height: 150, orientation: 'vertical', style: 'itemTitle' }),
    ),
    ...record.jobRisks.map((e, i) => craftRow(
        craftCell((i + 1).toString().padStart(2, '0'), { colSpan: 2 }),
        craftCell(e.name, { colSpan: 7 }),
        craftCell(e.activity, { colSpan: 10 }),
        craftCell(e.months.toString(), { colSpan: 5 }),
        craftCell(e.physicalRiskHighTemperature ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.physicalRiskLowTemperature ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.physicalRiskIonicRadiation ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.physicalRiskNonIonicRadiation ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.physicalRiskNoise ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.physicalRiskVibration ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.physicalRiskIllumination ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.physicalRiskVentilation ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.physicalRiskElectricFluid ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.physicalRiskOther ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskEntrapmentBetweenMachines ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskTrappingBetweenSurfaces ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskEntrapmentBetweenObjects ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskObjectFalling ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskSameLevelFalling ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskDifferentLevelFalling ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskElectricContact ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskSurfacesContact ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskParticlesProjection ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskFluidProjection ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskJab ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskCut ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskHitByVehicles ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskVehicleCollision ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.mechanicRiskOther ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.chemicalRiskSolid ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.chemicalRiskDust ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.chemicalRiskSmoke ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.chemicalRiskLiquid ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.chemicalRiskSteam ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.chemicalRiskAerosol ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.chemicalRiskMist ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.chemicalRiskGas ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.chemicalRiskOther ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.biologicalRiskVirus ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.biologicalRiskFungus ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.biologicalRiskBacteria ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.biologicalRiskParasites ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.biologicalRiskExposureToVectors ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.biologicalRiskExposureToWildlifeAnimals ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.biologicalRiskOther ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.ergonomicRiskManualHandlingLoads ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.ergonomicRiskRepetitiveMoves ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.ergonomicRiskForcedPostures ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.ergonomicRiskWorkWithPvd ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.ergonomicRiskOther ? 'x' : '', { alignment: 'center', fontSize: 10 }),
    ))
];

const jobRiskPreventionLayout: CraftItemFunc<PeriodicRecord> = (record) => [
    craftRow(
        craftTitle('Puesto de trabajo / Área', { rowSpan: 2, colSpan: 15 }),
        craftTitle('Actividades', { rowSpan: 2, colSpan: 18 }),
        craftTitle('Tiempo de trabajo (meses)', { rowSpan: 2, colSpan: 5 }),
        craftTitle('Psicosocial', { colSpan: 13 }),
        craftTitle('Medidas preventivas', { rowSpan: 2, colSpan: 19 }),
    ),
    craftRow(
        craftCell('Monotonía del trabajo', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Sobrecarga laboral', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Minuciosidad de la tarea', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Alta responsabilidad', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Autonomía  en la toma de decisiones', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Supervisión y estilos de dirección deficiente', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Conflicto de rol', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Falta de claridad en las funciones', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Incorrecta distribución del trabajo', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Turnos rotativos', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Relaciones interpersonales', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Inestabilidad laboral', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
        craftCell('Otros', { height: 175, orientation: 'vertical', style: 'itemTitle' }),
    ),
    ...record.jobRisks.map((e, i) => craftRow(
        craftCell((i + 1).toString().padStart(2, '0'), { colSpan: 2 }),
        craftCell(e.name, { colSpan: 13 }),
        craftCell(e.activity, { colSpan: 18 }),
        craftCell(e.months.toString(), { colSpan: 5 }),
        craftCell(e.psychosocialRiskMonotony ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskWorkOverload ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskThoroughnessOfTheTask ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskHighResponsibility ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskTakingResponsibilityAutonomy ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskSupervision ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskRoleConflict ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskNonFunctionClarify ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskBadWorkDistribution ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskRotativeShift ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskIntrapersonalRelations ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskJobInstability ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.psychosocialRiskOther ? 'x' : '', { alignment: 'center', fontSize: 10 }),
        craftCell(e.preventiveMeasure, { colSpan: 19 }),
    ))
]