# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Docker Image Deployment
on:
  push:
    branches:
      - develop
  pull_request: 
    branches:
      - develop
    types:
      - closed
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x']
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest .
        working-directory: .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image

    steps:
      - name: Check Repository
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        env:
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
          CONTAINER_NETWORK: ${{ secrets.CONTAINER_NETWORK }}
          LOCAL_FOLDER_MEDICAL_REPORT: ${{ secrets.LOCAL_FOLDER_MEDICAL_REPORT }}
          LOCAL_FOLDER_SIGNATURES: ${{ secrets.LOCAL_FOLDER_SIGNATURES }}
          LOCAL_FOLDER_EEQ: ${{ secrets.LOCAL_FOLDER_EEQ }}
          LOCAL_FOLDER_IPEGES: ${{ secrets.LOCAL_FOLDER_IPEGES }}
          CONTAINER_FOLDER_MEDICAL_REPORT: ${{ secrets.CONTAINER_FOLDER_MEDICAL_REPORT }}
          CONTAINER_FOLDER_SIGNATURES: ${{ secrets.CONTAINER_FOLDER_SIGNATURES }}
          CONTAINER_FOLDER_EEQ: ${{ secrets.CONTAINER_FOLDER_EEQ }}
          CONTAINER_FOLDER_IPEGES: ${{ secrets.CONTAINER_FOLDER_IPEGES }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_DATABASE: ${{ secrets.DATABASE_DATABASE }}
          JWT_DEFAULT_SECRET: ${{ secrets.JWT_DEFAULT_SECRET }}
          JWT_DEFAULT_EXPIRES_IN: ${{ secrets.JWT_DEFAULT_EXPIRES_IN }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          JWT_REFRESH_EXPIRES_IN: ${{ secrets.JWT_REFRESH_EXPIRES_IN }}
          API_KEY_EXPIRES_IN: ${{ secrets.API_KEY_EXPIRES_IN }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: CONTAINER_NAME,DOCKERHUB_USERNAME,DOCKERHUB_REPOSITORY,CONTAINER_NETWORK,LOCAL_FOLDER_MEDICAL_REPORT,LOCAL_FOLDER_SIGNATURES,LOCAL_FOLDER_EEQ,LOCAL_FOLDER_IPEGES,CONTAINER_FOLDER_MEDICAL_REPORT,CONTAINER_FOLDER_SIGNATURES,CONTAINER_FOLDER_EEQ,CONTAINER_FOLDER_IPEGES,ENVIRONMENT,DATABASE_TYPE,DATABASE_HOST,DATABASE_PORT,DATABASE_USERNAME,DATABASE_PASSWORD,DATABASE_DATABASE,JWT_DEFAULT_SECRET,JWT_DEFAULT_EXPIRES_IN,JWT_REFRESH_SECRET,JWT_REFRESH_EXPIRES_IN,API_KEY_EXPIRES_IN
          script: |
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker rmi $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest || true
            docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest
            docker run -d \
              --network=$CONTAINER_NETWORK \
              --name $CONTAINER_NAME \
              -p 3001:3001 \
              -v $LOCAL_FOLDER_MEDICAL_REPORT:$CONTAINER_FOLDER_MEDICAL_REPORT \
              -v $LOCAL_FOLDER_SIGNATURES:$CONTAINER_FOLDER_SIGNATURES \
              -v $LOCAL_FOLDER_EEQ:$CONTAINER_FOLDER_EEQ \
              -v $LOCAL_FOLDER_IPEGES:$CONTAINER_FOLDER_IPEGES \
              -e APP_ENVIRONMENT= $ENVIRONMENT \
              -e DATABASE_SQL_TYPE = $DATABASE_TYPE \
              -e DATABASE_SQL_HOST = $DATABASE_HOST \
              -e DATABASE_SQL_PORT = $DATABASE_PORT \
              -e DATABASE_SQL_USERNAME = $DATABASE_USERNAME \
              -e DATABASE_SQL_PASSWORD = $DATABASE_PASSWORD \
              -e DATABASE_SQL_DATABASE = $DATABASE_DATABASE \
              -e JWT_DEFAULT_SECRET = $JWT_DEFAULT_SECRET \
              -e JWT_DEFAULT_EXPIRES_IN = $JWT_DEFAULT_EXPIRES_IN \
              -e JWT_REFRESH_SECRET = $JWT_REFRESH_SECRET \
              -e JWT_REFRESH_EXPIRES_IN = $JWT_REFRESH_EXPIRES_IN \
              -e APIKEY_EXPIRES_IN = $API_KEY_EXPIRES_IN \
              $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest \